# Generated by Django 4.1.7 on 2023-06-12 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_message_message_image_offer_message_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_product', to='store.category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='delivery_time',
            field=models.CharField(choices=[('1 día', '1 día'), ('2 días', '2 días'), ('3 días', '3 días'), ('4 días', '4 días'), ('5 días', '5 días'), ('6 días', '6 días'), ('1 semana', '1 semana'), ('2 semanas', '2 semanas'), ('3 semanas', '3 semanas'), ('1 mes', '1 mes'), ('2 meses', '2 meses')], default='1 día', max_length=20, null=True),
        ),
    ]
