# Generated by Django 4.1.7 on 2023-06-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_offer_category_offer_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
